// Generated by CoffeeScript 1.6.2
(function() {
  var size, x;

  size = function() {
    var h;

    h = $(window).height();
    console.log(h);
    return $('#title').height(h).css('line-height', h + 'px');
  };

  $(document).ready(function() {
    size();
    $(window).scroll(function() {
      if ($(window).scrollTop() > 0) {
        return $('#toolbar:not(.inner)').addClass('fixed');
      } else {
        return $('#toolbar:not(.inner)').removeClass('fixed');
      }
    });
    $('#title .big-button').click(function() {
      $("html, body").animate({
        scrollTop: $('#title').height() - 55
      }, 300);
      return false;
    });
    return $('#Order').modal();
  });

  x = void 0;

  $(window).resize(function() {
    return x = setTimeout(size, 300);
  });

}).call(this);
